### PR TITLE
 OroCommerceDocs/typo

### PR DESCRIPTION
**Pull request by AminMkh**

### CODE REVIEW

**Comment by orocla** [comment]
Thank you for your pull request.

It looks like this may be your first contribution to an Oro, Inc. open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at http://www.orocommerce.com/contributor-license-agreement/

If you've already signed the CLA, it's possible we don't have your GitHub username or you're using a different email address. GitHub uses the email address you set in your local Git configuration to associate commits with your GitHub account. Please sign the CLA again using the correct GitHub username and email address or see this help article on [setting the email on your git commits](https://help.github.com/articles/setting-your-email-in-git/).

Once you've signed the CLA, please allow for some time for the submission to be processed.

**Comment by AminMkh** [comment]
Sure, I tried going to https://www.orocommerce.com/contributor-license-agreement but I don't see any sign or I agree button, 

at the bottom of the page I see

>         Indemnification. Contributor agrees to indemnify, defend and hold harmless Oro, its officers, directors, employees, agents, shareholders, and licensors from and against any losses, damages, fines and expenses (including attorneys’ fees and costs) arising out of or relating to any third party claims that arise from or are in connection with: (i) Contributor’s violation of any terms of this Agreement; (ii) distribution and/or use of the Contributions, including any breach of Third Party IP; and/or (iii) the Contributions. Oro shall provide Contributor with written notice of the claim, permit Contributor to control the defense, settlement, adjustment or compromise of any such claim, and reasonably cooperate with Contributor in the defense and any related settlement action. Oro reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification by Contributor
> Loading…

**Comment by mbessolov** [comment]
@AminMkh the form has been temporarily unavailable. It's back online now.

**Comment by AminMkh** [comment]
ok done :)

Note there are lots of out dated links/anchor tags in the documentation, plus a lot of Orocommerce features undocumented yet :(

**Comment by mkudelya** [comment]
Your PR has been merged. Changes from PR will be synced to the public repository in a few days. Thank you.

**Pull request closed without merging**
